export const classesData = [
  {
    class_name: "Boxing",
    category: "Fitness",
    class_code: "boxing",
    capacity: 20,
    difficulty_level: "Intermediate",
    description: "High-intensity boxing class for fitness.",
    is_active: true,
    schedule: {
      start_time: "07:00 AM",
      end_time: "08:00 AM",
      location: "Gym A - Room 1",
      status: "Scheduled",
    },
    media_code: "boxing324",
  },
  {
    class_name: "Yoga",
    category: "Wellness",
    class_code: "yoga",
    capacity: 18,
    difficulty_level: "Beginner",
    description: "A relaxing yoga class focusing on flexibility and mindfulness.",
    is_active: true,
    schedule: {
      start_time: "08:00 AM",
      end_time: "09:00 AM",
      location: "Yoga Studio",
      status: "Scheduled",
    },
    media_code: "yoga567",
  },
  {
    class_name: "Cycling",
    category: "Cardio",
    class_code: "cycling",
    capacity: 25,
    difficulty_level: "Intermediate",
    description: "An energetic indoor cycling class with music.",
    is_active: true,
    schedule: {
      start_time: "07:30 AM",
      end_time: "08:30 AM",
      location: "Spin Room",
      status: "Scheduled",
    },
    media_code: "cycling679",
  },
  {
    class_name: "Strength Training",
    category: "Fitness",
    class_code: "strength",
    capacity: 25,
    difficulty_level: "Advanced",
    description: "A high-intensity class focused on building strength.",
    is_active: true,
    schedule: {
      start_time: "06:00 PM",
      end_time: "07:00 PM",
      location: "Weight Room",
      status: "Scheduled",
    },
    media_code: "strength439",
  },
  {
    class_name: "Cardio",
    category: "Cardio",
    class_code: "cardio",
    capacity: 22,
    difficulty_level: "Intermediate",
    description: "A high-energy cardio workout to boost endurance.",
    is_active: true,
    schedule: {
      start_time: "05:30 PM",
      end_time: "06:30 PM",
      location: "Gym B - Open Floor",
      status: "Scheduled",
    },
    media_code: "cardio765",
  },
  {
    class_name: "Dance",
    category: "Fitness",
    class_code: "dance",
    capacity: 20,
    difficulty_level: "Beginner",
    description: "A fun dance class to improve coordination and fitness.",
    is_active: true,
    schedule: {
      start_time: "09:00 AM",
      end_time: "10:00 AM",
      location: "Dance Studio",
      status: "Scheduled",
    },
    media_code: "dance296",
  },
];
