export const classesData = [
  {
    class_name: "Kickboxing",
    category: "Fitness",
    class_code: "kickboxing",
    capacity: 20,
    difficulty_level: "Intermediate",
    description: "Improve your skills and fitness with professional kickboxing classes. Learn powerful striking techniques and defensive moves while enjoying a full-body workout that enhances strength, coordination, and flexibility.",
    is_active: true,
    schedule: {
      start_time: "07:00 AM",
      end_time: "08:00 AM",
      location: "Gym A - Room 1",
      status: "Scheduled",
    },
    media_code: "kickboxing324",
    trainer_id: "user_1",  
  },
  {
    class_name: "Yoga",
    category: "Wellness",
    class_code: "yoga",
    capacity: 18,
    difficulty_level: "Beginner",
    description: "Yoga is the evolution of meditation meant for anyone of any age.  Through a daily practice of proven techniques, you awaken your own strength, qualities and energy that lies dormant within you.",
    is_active: true,
    schedule: {
      start_time: "08:00 AM",
      end_time: "09:00 AM",
      location: "Yoga Studio",
      status: "Scheduled",
    },
    media_code: "yoga567",
    trainer_id: "user_2", 
  },
  {
    class_name: "Cycling",
    category: "Cardio",
    class_code: "cycling",
    capacity: 25,
    difficulty_level: "Intermediate",
    description: "Our dynamic, low-impact Cycling Classes are set to motivating music and take you through a variety of sprints, hills and valleys designed to build endurance and burn calories.",
    is_active: true,
    schedule: {
      start_time: "07:30 AM",
      end_time: "08:30 AM",
      location: "Spin Room",
      status: "Scheduled",
    },
    media_code: "cycling679",
    trainer_id: "user_5", 
  },
  {
    class_name: "Strength Training",
    category: "Fitness",
    class_code: "strength",
    capacity: 25,
    difficulty_level: "Advanced",
    description: "Rise to the challenge with GoodLife’s Strength Classes. Build muscle, achieve your weight loss goals and maintain bone density, no matter your fitness level.",
    is_active: true,
    schedule: {
      start_time: "06:00 PM",
      end_time: "07:00 PM",
      location: "Weight Room",
      status: "Scheduled",
    },
    media_code: "strength439",
    trainer_id: "user_3",  
  },
  {
    class_name: "Cardio",
    category: "Cardio",
    class_code: "cardio",
    capacity: 22,
    difficulty_level: "Intermediate",
    description: "Our energetic Cardio Classes work your entire body and get your heart pumping. Get motivated, push past your limits and torch calories with a wide variety of endurance-building classes.",
    is_active: true,
    schedule: {
      start_time: "05:30 PM",
      end_time: "06:30 PM",
      location: "Gym B - Open Floor",
      status: "Scheduled",
    },
    media_code: "cardio765",
    trainer_id: "user_6", 
  },
  {
    class_name: "Dance",
    category: "Fitness",
    class_code: "dance",
    capacity: 20,
    difficulty_level: "Beginner",
    description: "Move and groove your way to a healthier body and mind. GoodLife’s Dance Fitness Classes are a combination of high-energy music and easy-to-follow dance moves that’ll leave you wanting more.",
    is_active: true,
    schedule: {
      start_time: "09:00 AM",
      end_time: "10:00 AM",
      location: "Dance Studio",
      status: "Scheduled",
    },
    media_code: "dance296",
    trainer_id: "user_4",  
  },
];
