export const users = [
  {
    user_id: "user_1",
    first_name: "Edwin",
    last_name: "A",
    email: "edwina@example.com",
    phone_number: "123-456-7890",
    username: "edwina",
    password_hash: "hashedpassword",
    role: "trainer", 
    gender: "male",
    address: "123 St, City, Country",
    date_joined: "2021-01-01",
    last_updated_date: "2023-01-01",
    image: "Edwin.jpg",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 50,
        employment_status: "full-time",
        monthly_salary: 4000,
      },
    },
    trainer_details: {
      description: "An expert in strength training and nutrition, Edwin has over 15 years of experience in designing personalized fitness programs.",
      assigned_classes: ["kickboxing"], 
    },
  },
  {
    user_id: "user_2",
    first_name: "Pari",
    last_name: "S",
    email: "paris@example.com",
    phone_number: "987-654-3210",
    username: "paris",
    password_hash: "hashedpassword",
    role: "trainer", 
    gender: "female",
    address: "456 Ave, City, Country",
    date_joined: "2021-06-01",
    last_updated_date: "2023-06-01",
    image: "pari.jpg",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 45,
        employment_status: "part-time",
        monthly_salary: 2500,
      },
    },
    trainer_details: {
      description: "With a deep passion for flexibility and mindfulness, Pari has been teaching yoga for over 8 years.",
      assigned_classes: ["yoga"], 
    },
  },
  {
    user_id: "user_3",
    first_name: "Nigh",
    last_name: "G",
    email: "nighg@example.com",
    phone_number: "333-444-5555",
    username: "nighg",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "101 Blvd, City, Country",
    date_joined: "2023-07-01",
    last_updated_date: "2023-07-01",
    image: "nigh.avif",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 60,
        employment_status: "part-time",
        monthly_salary: 2000,
      },
    },
    trainer_details: {
      description: "Passionate about healthy eating and meal planning, Nigh uses evidence-based strategies to help clients develop sustainable eating habits.",
      assigned_classes: ["strength"],
    },
  },
  {
    user_id: "user_4",
    first_name: "Kozeta",
    last_name: "A",
    email: "kozetaa@example.com",
    phone_number: "555-555-5555",
    username: "kozetaa",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "female",
    address: "789 Rd, City, Country",
    date_joined: "2023-03-01",
    last_updated_date: "2023-06-01",
    image: "Kozeta.jpg",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 55,
        employment_status: "full-time",
        monthly_salary: 4000,
      },
    },
    trainer_details: {
      description: "Certified personal trainer with 10 years of experience, Kozeta specializes in creating customized workout routines that help clients reach their fitness goals.",
      assigned_classes: ["dance"], 
    },
  },
  {
    user_id: "user_5",
    first_name: "Teddy",
    last_name: "A",
    email: "teddya@example.com",
    phone_number: "222-333-4444",
    username: "teddya",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "555 St, City, Country",
    date_joined: "2022-05-01",
    last_updated_date: "2023-05-01",
    image: "Teddy.jpg",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 50,
        employment_status: "full-time",
        monthly_salary: 3500,
      },
    },
    trainer_details: {
      description: "Teddy helps clients improve their endurance and heart health through tailored cardiovascular training programs.",
      assigned_classes: ["cycling"],
    },
  },
  {
    user_id: "user_6",
    first_name: "Augustine",
    last_name: "B",
    email: "augustineb@example.com",
    phone_number: "111-222-3333",
    username: "augustineb",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "777 Blvd, City, Country",
    date_joined: "2021-08-01",
    last_updated_date: "2023-08-01",
    image: "Aug.jpg",
    employee: {
      specialties: {
        employee_type: "Trainer",
        hourly_rate: 50,
        employment_status: "part-time",
        monthly_salary: 2500,
      },
    },
    trainer_details: {
      description: "Augustine is a Pilates instructor with a focus on core strength and stability.",
      assigned_classes: ["cardio"], 
    },
  },
];
