export const users = [
  {
    user_id: "user_1",
    first_name: "Edwin",
    last_name: "A",
    email: "edwina@example.com",
    phone_number: "123-456-7890",
    username: "edwina",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "123 St, City, Country",
    image: "Edwin.jpg",
    employee: {
      specialties: {
        employee_type: "Kickboxing Instructor",
        hourly_rate: 50,
        employment_status: "full-time",
        monthly_salary: 4000,
      },
    },
    trainer_details: {
      description: "Edwin is a skilled kickboxing instructor who helps clients build strength and endurance.",
      assigned_classes: ["kickboxing"],
    },
  },
  {
    user_id: "user_2",
    first_name: "Pari",
    last_name: "S",
    email: "paris@example.com",
    phone_number: "987-654-3210",
    username: "paris",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "female",
    address: "456 Ave, City, Country",
    image: "pari.jpg",
    employee: {
      specialties: {
        employee_type: "Yoga Instructor",
        hourly_rate: 45,
        employment_status: "part-time",
        monthly_salary: 2500,
      },
    },
    trainer_details: {
      description: "Pari guides students in improving flexibility, balance, and mindfulness through yoga.",
      assigned_classes: ["yoga"],
    },
  },
  {
    user_id: "user_3",
    first_name: "Nghi",
    last_name: "G",
    email: "nghig@example.com",
    phone_number: "333-444-5555",
    username: "nghig",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "female",
    address: "101 Blvd, City, Country",
    image: "nghi.avif",
    employee: {
      specialties: {
        employee_type: "Strength Training",
        hourly_rate: 60,
        employment_status: "part-time",
        monthly_salary: 2000,
      },
    },
    trainer_details: {
      description: "Nghi specializes in strength training, helping clients build muscle and improve performance.",
      assigned_classes: ["strength"],
    },
  },
  {
    user_id: "user_4",
    first_name: "Kozeta",
    last_name: "A",
    email: "kozetaa@example.com",
    phone_number: "555-555-5555",
    username: "kozetaa",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "female",
    address: "789 Rd, City, Country",
    image: "Kozeta.jpg",
    employee: {
      specialties: {
        employee_type: "Dance Instructor",
        hourly_rate: 55,
        employment_status: "full-time",
        monthly_salary: 4000,
      },
    },
    trainer_details: {
      description: "Kozeta brings energy and creativity to dance classes, helping students refine their skills.",
      assigned_classes: ["dance"],
    },
  },
  {
    user_id: "user_5",
    first_name: "Teddy",
    last_name: "A",
    email: "teddya@example.com",
    phone_number: "222-333-4444",
    username: "teddya",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "555 St, City, Country",
    image: "Teddy.jpg",
    employee: {
      specialties: {
        employee_type: "Cycling Instructor",
        hourly_rate: 50,
        employment_status: "full-time",
        monthly_salary: 3500,
      },
    },
    trainer_details: {
      description: "Teddy helps clients enhance endurance and cardiovascular health through cycling.",
      assigned_classes: ["cycling"],
    },
  },
  {
    user_id: "user_6",
    first_name: "Augustine",
    last_name: "B",
    email: "augustineb@example.com",
    phone_number: "111-222-3333",
    username: "augustineb",
    password_hash: "hashedpassword",
    role: "trainer",
    gender: "male",
    address: "777 Blvd, City, Country",
    image: "Aug.jpg",
    employee: {
      specialties: {
        employee_type: "Cardio Instructor",
        hourly_rate: 50,
        employment_status: "part-time",
        monthly_salary: 2500,
      },
    },
    trainer_details: {
      description: "Augustine focuses on improving stamina and heart health through cardio workouts.",
      assigned_classes: ["cardio"],
    },
  },
];
