export const users = [
    {
      user_id: "user_1",
      first_name: "John",
      last_name: "Doe",
      email: "johndoe@example.com",
      phone_number: "123-456-7890",
      username: "johndoe",
      password_hash: "hashedpassword",
      role: "member",
      gender: "male",
      address: "123 St, City, Country",
      date_joined: "2022-01-01",
      last_updated_date: "2023-01-01",
      membership: {
        start_date: "2022-01-01",
        end_date: "2023-01-01",
        plan_code: "basic",
        status: "active",
        renewal_date: "2023-01-01",
      },
    },
    {
      user_id: "user_2",
      first_name: "Jane",
      last_name: "Smith",
      email: "janesmith@example.com",
      phone_number: "987-654-3210",
      username: "janesmith",
      password_hash: "hashedpassword",
      role: "admin",
      gender: "female",
      address: "456 Ave, City, Country",
      date_joined: "2021-06-01",
      last_updated_date: "2023-06-01",
      membership: {
        start_date: "2021-06-01",
        end_date: "2022-06-01",
        plan_code: "premium",
        status: "inactive",
        renewal_date: "2022-06-01",
      },
    },
    {
      user_id: "user_3",
      first_name: "Mike",
      last_name: "Johnson",
      email: "mikejohnson@example.com",
      phone_number: "555-555-5555",
      username: "mikej",
      password_hash: "hashedpassword",
      role: "member",
      gender: "male",
      address: "789 Rd, City, Country",
      date_joined: "2023-03-01",
      last_updated_date: "2023-06-01",
      membership: {
        start_date: "2023-03-01",
        end_date: "2024-03-01",
        plan_code: "gold",
        status: "active",
        renewal_date: "2024-03-01",
      },
    },
    {
      user_id: "user_4",
      first_name: "Emily",
      last_name: "Williams",
      email: "emilywilliams@example.com",
      phone_number: "333-444-5555",
      username: "emilyw",
      password_hash: "hashedpassword",
      role: "member",
      gender: "female",
      address: "101 Blvd, City, Country",
      date_joined: "2023-07-01",
      last_updated_date: "2023-07-01",
      membership: {
        start_date: "2023-07-01",
        end_date: "2024-07-01",
        plan_code: "premium",
        status: "active",
        renewal_date: "2024-07-01",
      },
    },
];
  